### ISSUE TITLE
Prefix highlight ?

### ISSUE THREAD

**Issue by luique16** [odedlaz/tmux-onedark-theme#19]
I don't know if this is an issue, but i really want a native prefix highlight on this theme, i love the theme, but i NEED to see when i press my prefix bc i do it automatically lol

If you have a way to add it just tell me too.

Thank you! 🇧🇷

**Comment by Mr-Tao** [comment]
I use [tmux-prefix-highlight](https://github.com/tmux-plugins/tmux-prefix-highlight) plugin for that. That said I would like this theme to integrate that plugin better, perhaps in a manner similar to how [nord-tmux](https://github.com/arcticicestudio/nord-tmux) does that.

**Comment by luique16** [comment]
> I use [tmux-prefix-highlight](https://github.com/tmux-plugins/tmux-prefix-highlight) plugin for that. That said I would like this theme to integrate that plugin better, perhaps in a manner similar to how [nord-tmux](https://github.com/arcticicestudio/nord-tmux) does that.

Thank you! 😃
