### ISSUE TITLE
Background transparency can't be enabled

### ISSUE THREAD

**Issue by maxigaz** [odedlaz/tmux-onedark-theme#5]
With the theme being installed, I don't know how to enable background transparency. Without the theme, transparency works well in both Konsole and Yakuake under Manjaro Linux, with and without tmux.

I have the following in my .tmux.conf (for true colour):

```
set-option -ga terminal-overrides ",xterm-256color:Tc"
```

**Comment by Shaxine** [comment]
@maxigaz Did you solve the issue? Would you care to share how to keep the background transparency?

**Comment by maxigaz** [comment]
@Shaxine I've just tackled this issue again, and finally I got some results!

I believe the problem is that the theme sets the whole background colour as completely solid, overriding the background setting of the terminal emulator.

So, the only solution that seems to be working for me is open `~/.tmux/plugins/tmux-onedark-theme/tmux-onedark-theme.tmux`, find the lines with `bg` and `#282c34` (the background colour set by the theme) in them, and replace the latter with the word `default`. 

It takes some trial and error to see where `#282c34` should and shouldn't be replaced for the desired effect. (I don't recommend overriding the variable `onedark_black` because it makes some messages illegible and powerline characters look funny.)

In addition, you may also want to set `#282c34` as a background colour inside your terminal emulator settings unless the current one suits you. (I haven't tried it yet with Konsole.)

I'll finish making my own modifications later and maybe create a fork specifically for transparent background.

**Comment by duganchen** [comment]
I've put in a pull request to fix this properly, but for now, you can work around the problem by putting this after at the end of tmux.conf:
```
# Just to show that the two new lines come after these:
set -g @plugin 'odedlaz/tmux-onedark-theme'
run '~/.tmux/plugins/tpm/tpm'

# These make tmux transparent again
set -g "window-style" "bg=default"
set -g "window-active-style" "bg=default"
```

I'm not sure why this was closed. What I can say is that while the above Konsole colorscheme was reported to maintain transparency with this theme, it did not do so after I used the following script to convert it to Alacritty:

https://github.com/jwilm/alacritty/issues/1093

There is no Alacritty color scheme that maintains transparency when used with this theme. Nor, at present, would I expect there to be.

**Comment by maxigaz** [comment]
I've just tried using the code you shared above, @duganchen (putting it at the bottom of .tmux.conf). It does enable background transparency in multiple Konsole themes, indeed.

I've also noticed that it has an effect on the text colour as well, following whatever is set in Konsole instead of what's in the tmux theme. (Weird, since you only defined the background here.)

**Comment by duganchen** [comment]
That's interesting. Try this:

    set -g "window-style" "fg=#5c6370,bg=default"
    set -g "window-active-style" "fg=#aab2bf,bg=default"

That's what's in the pull request.

**Comment by maxigaz** [comment]
That works. Thank you!

**Comment by odedlaz** [comment]
Fixed in https://github.com/odedlaz/tmux-onedark-theme/pull/9 :)

**Comment by Axedyson** [comment]
This is how it looks like without the workaround:
![image](https://user-images.githubusercontent.com/28491857/93564642-51b76d00-f98a-11ea-82f3-55afa9b6531f.png)


Still doesn't work perfectly I still need the following lines set after `run '~/.tmux/plugins/tpm/tpm'`

```
set -g "window-style" "fg=#5c6370,bg=default"
set -g "window-active-style" "fg=#aab2bf,bg=default"
```
After those lines are set, this is now how it looks, which is what I want:
![image](https://user-images.githubusercontent.com/28491857/93564763-86c3bf80-f98a-11ea-8c95-5a0aca337e71.png)

It seems like the theme is greying things out a little bit by default😕
